"""Generates a synthetic methods paper describing a real, implementable technique.

Used by tests and by the offline demo path. The technique described is genuine
(bias-corrected fuzzy c-means), so extraction quality is meaningful.

Deliberately synthetic: the paper this project is modelled on (Ahmed et al.) is
IEEE-copyrighted and must never enter the repository. This stand-in carries the
same algorithmic content in text we own.
"""

from pathlib import Path

import fitz

PAGES = [
    """SYNTHETIC TEST FIXTURE - NOT A REAL PUBLICATION

This document was generated by scripts/make_sample_paper.py to exercise skill
extraction offline. It paraphrases a well-known technique in text written for
this project. It is not the work of any author, has never been published, and
must not be cited. The paper this project is modelled on (Ahmed et al., IEEE)
is copyrighted and is deliberately absent from this repository.

A Modified Fuzzy C-Means Algorithm for Bias Field Estimation
and Segmentation of MRI Data
(synthetic stand-in)

Abstract
We present a modification of the fuzzy c-means objective function that
compensates for intensity inhomogeneity and allows the labelling of a pixel
to be influenced by its immediate neighbourhood. The neighbourhood term acts
as a regularizer and biases the solution toward piecewise homogeneous
labelling.""",
    """2. Method

The standard fuzzy c-means objective is modified by adding a neighbourhood
regularization term. The objective function is

  J = sum_i sum_k u_ik^p ||y_k - v_i||^2
      + (alpha / N_R) sum_i sum_k u_ik^p sum_{y_r in N_k} ||y_r - v_i||^2

where u_ik is the membership of voxel k in class i, v_i is the centroid of
class i, N_k is the set of neighbours of voxel k, and N_R is the cardinality
of that neighbourhood.

We set the neighbourhood weight alpha = 0.7 in all experiments reported here.
The fuzzifier is fixed at p = 2, which is the conventional choice.""",
    """2.1 Optimization

Minimizing J with respect to the memberships gives the update

  u_ik = 1 / sum_j ( D_ik / D_jk )^(1/(p-1))

where D_ik = ||y_k - v_i||^2 + (alpha / N_R) sum_{y_r in N_k} ||y_r - v_i||^2.

The centroid update is

  v_i = sum_k u_ik^p ( y_k + (alpha / N_R) sum_r y_r ) / ( (1 + alpha) sum_k u_ik^p )

Centroids are initialized using k-means on the intensity histogram.
The algorithm alternates between the membership update and the centroid
update until convergence. The algorithm halts when the maximum change in any
centroid falls below epsilon = 0.001, or after 100 iterations.""",
    """2.2 Bias field estimation

The observed intensity is modelled as the product of the true intensity and a
smooth multiplicative bias field. Working in the log domain converts this to
an additive model. The bias field at voxel k is estimated as

  beta_k = y_k - sum_i u_ik^p v_i / sum_i u_ik^p

and is smoothed with a mean filter before being subtracted from the log-domain
image at each iteration.

3. Preprocessing

Intensities are normalized to the range [0, 1] before clustering. Background
voxels are excluded using a simple intensity threshold at the 5th percentile,
which prevents the background from dominating the centroid estimates.

4. Failure modes

The method is sensitive to initialization when tissue contrast is low, and the
neighbourhood term over-smooths thin structures when alpha is set too high.""",
]


def build(out_path: Path) -> Path:
    doc = fitz.open()
    for body in PAGES:
        page = doc.new_page()
        page.insert_textbox(
            fitz.Rect(60, 60, 540, 760), body, fontsize=10.5, fontname="helv", align=0
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(out_path))
    doc.close()
    return out_path


if __name__ == "__main__":
    p = build(Path(__file__).resolve().parents[1] / "fixtures" / "sample_methods_paper.pdf")
    print(f"wrote {p}")
